title: My Blog
description: Contains my experiences in the world of computer science and some other stuff too ;).

url: http://sauravchandra1.github.io/blog
baseurl: "/blog"
paginate_path: "page:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   github: sauravchandra1
   email: sauravchandra125@gmail.com

google_analytics: "UA-121657139-2"
